//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5HomeworkWeek1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶資料概要
    {
        public string 客戶名稱 { get; set; }
        public Nullable<int> 客戶銀行總數 { get; set; }
        public Nullable<int> 客戶聯絡人總數 { get; set; }
    }
}
